services:
  nginx:
    image: nginx:latest
    container_name: spoodler_nginx
    ports:
      - "8080:80"
      - "8443:443"  # Expose HTTPS on port 8443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./spoodler:/var/www/html
      - ./docker/nginx/ssl:/etc/nginx/ssl  # Mount the SSL certificates
    depends_on:
      - php
    networks:
      - spoodler_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: spoodler_php
    volumes:
      - ./spoodler:/var/www/html
    depends_on:
      - db
    networks:
      - spoodler_network

  db:
    image: mysql:8.0
    container_name: spoodler_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_DATABASE: ${DB_NAME:-spoodler}
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - spoodler_network
      
  test_db:
    image: mysql:8.0
    container_name: spoodler_test_db
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spoodler_test
      MYSQL_USER: spoodler_user
      MYSQL_PASSWORD: spoodler_password
    ports:
      - "3307:3306"
    networks:
      - spoodler_network

networks:
  spoodler_network:
    driver: bridge
