services:
  nginx:
    image: nginx:latest
    container_name: spoodler_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./spoodler:/var/www/html # Could it be ./spoodler/ui instead?
    depends_on:
      - php
    networks:
      - spoodler_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: spoodler_php
    volumes:
      - ./spoodler:/var/www/html
    depends_on:
      - db
    networks:
      - spoodler_network

  db:
    image: mysql:8.0
    container_name: spoodler_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - spoodler_network

networks:
  spoodler_network:
    driver: bridge
