FROM node:22.13.1-alpine

WORKDIR /app/spoodler-frontend

# Documentation about which port will be used. Not actually exposing anything
EXPOSE 3443

# Start the development server
CMD ["npm", "run", "dev"]
